import Head from 'next/head'
import Sidebar from '@/components/Sidebar';
import styled from "styled-components"

export default function Home() {
  return (
      <div>
      <Head>
        <title>Whatsapp By JP</title>
        <meta name="description" content="Generated by Jenil Patel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/2042px-WhatsApp.svg.png" />
      </Head>
         {/* <h1>Jay Shree RAM Jay Shree KASHTBHANJANDEV</h1>  */}
         <Sidebar />
         </div>
  )
}
